//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGEVENT
    {
        public string PROCESSNAME { get; set; }
        public Nullable<int> INCIDENT { get; set; }
        public string STEPID { get; set; }
        public string TASKID { get; set; }
        public string TASKUSER { get; set; }
        public Nullable<int> EVENTTYPE { get; set; }
        public string ACTIVATIONID { get; set; }
        public Nullable<System.DateTime> EVENTTIME { get; set; }
        public string STEPLABEL { get; set; }
        public string NOTES { get; set; }
        public string SUMMARY { get; set; }
        public byte[] EVALINFO { get; set; }
        public int ARCHIVED { get; set; }
        public Nullable<int> PROCESSVERSION { get; set; }
    }
}
