//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEMBER
    {
        public int MEMBERID { get; set; }
        public int MEMBERTYPE { get; set; }
        public string NAME { get; set; }
        public string FULLNAME { get; set; }
        public int GID { get; set; }
        public Nullable<int> BUSINESSID { get; set; }
        public Nullable<int> WEIGHT { get; set; }
        public Nullable<int> SEQ { get; set; }
        public byte[] MISCDATA { get; set; }
    
        public virtual GROUP GROUP { get; set; }
    }
}
