//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROCESS
    {
        public string PROCESSNAME { get; set; }
        public int PROCESSVERSION { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<int> MAXINC { get; set; }
        public Nullable<int> PROCMANAGERTYPE { get; set; }
        public string PROCMANAGER { get; set; }
        public byte[] DBINFO { get; set; }
        public string DESCRIPTION { get; set; }
        public byte[] MAPDATA { get; set; }
        public byte[] MAINSS { get; set; }
        public byte[] PROCESSDATA { get; set; }
        public Nullable<int> LAUNCHTYPE { get; set; }
        public Nullable<int> LAUNCHPROPS { get; set; }
        public Nullable<System.DateTime> NEXTLAUNCHTIME { get; set; }
        public Nullable<int> MAPVERSION { get; set; }
        public byte[] PROCESSSCHEMA { get; set; }
        public string SCHEMADATA { get; set; }
        public byte[] PROCESSRULES { get; set; }
        public byte[] ALIASES { get; set; }
        public string LABEL { get; set; }
        public string REPID { get; set; }
        public byte[] TYPESCHEMA { get; set; }
        public byte[] PROCESSASSEMBLY { get; set; }
        public byte[] ASSEMBLYCONFIG { get; set; }
        public byte[] SCHEMACONFIG { get; set; }
        public byte[] PROCESSFORMULA { get; set; }
        public byte[] TYPEASSEMBLY { get; set; }
        public string PROCESSID { get; set; }
    }
}
