//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROCESSSTEP
    {
        public string PROCESSNAME { get; set; }
        public int PROCESSVERSION { get; set; }
        public string STEPID { get; set; }
        public string STEPLABEL { get; set; }
        public Nullable<int> STEPTYPE { get; set; }
        public Nullable<int> STEPPROPS { get; set; }
        public Nullable<int> RECIPIENTTYPE { get; set; }
        public string RECIPIENT { get; set; }
        public string FLOBOTNAME { get; set; }
        public Nullable<int> MINRESP { get; set; }
        public byte[] STEPINFO { get; set; }
        public byte[] EVENTACTIONS { get; set; }
        public byte[] VARINFO { get; set; }
        public byte[] LOCALSS { get; set; }
        public Nullable<double> FLOBOTFAILINTERVAL { get; set; }
        public string ORGANIZATION { get; set; }
        public Nullable<int> MAPVERSION { get; set; }
        public byte[] STEPSCHEMA { get; set; }
        public string STEPDATA { get; set; }
        public byte[] STEPRULES { get; set; }
        public byte[] STEPASSEMBLY { get; set; }
        public byte[] STEPFORMULA { get; set; }
    }
}
