//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORTSRIGHT
    {
        public string REPORTID { get; set; }
        public string REPORTNAME { get; set; }
        public int RECIPIENTTYPE { get; set; }
        public string RECIPIENT { get; set; }
        public string ORGNAME { get; set; }
        public Nullable<int> RIGHTS { get; set; }
        public Nullable<bool> ISOWNER { get; set; }
    }
}
