//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBPROC
    {
        public string PNAME { get; set; }
        public int PINCIDENT { get; set; }
        public string PTASKID { get; set; }
        public string CNAME { get; set; }
        public Nullable<int> CINCIDENT { get; set; }
        public string PSTEPID { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<int> WAITFORCHILD { get; set; }
    }
}
