//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BPM_READ_KNOW
    {
        public string CID { get; set; }
        public string PRC_NAME { get; set; }
        public string STEP_NAME { get; set; }
        public Nullable<int> INCIDENT { get; set; }
        public string SUMMARY { get; set; }
        public string SENDER_CID { get; set; }
        public string SENDER_NAME { get; set; }
        public Nullable<System.DateTime> SEND_DATE { get; set; }
        public string TASK_ID { get; set; }
        public string RK_USER_CID { get; set; }
        public string RK_USER_NAME { get; set; }
        public Nullable<System.DateTime> READ_DATE { get; set; }
        public Nullable<int> RK_STATUS { get; set; }
        public string RK_NOTE { get; set; }
    }
}
