//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BPM_TASK_AUTOASSIGNED
    {
        public string CID { get; set; }
        public string SYSTEM_CID { get; set; }
        public string SYSTEM_NAME { get; set; }
        public string UTA_ASSIGNEDNAME { get; set; }
        public string UTA_PROCESSNAME { get; set; }
        public string UTA_PROCESSTYPE_CID { get; set; }
        public string UTA_PROCESSTYPE_NAME { get; set; }
        public string UTA_TASKUSER { get; set; }
        public string UTA_TASKUSER_CID { get; set; }
        public string UTA_TASKUSER_NAME { get; set; }
        public string UTA_ASSTOUSER { get; set; }
        public string UTA_ASSTOUSER_CID { get; set; }
        public string UTA_ASSTOUSER_NAME { get; set; }
        public Nullable<System.DateTime> UTA_STARTTIME { get; set; }
        public Nullable<System.DateTime> UTA_ENDTIME { get; set; }
        public Nullable<System.DateTime> UTA_OPERTIME { get; set; }
        public Nullable<int> UTA_STATUS { get; set; }
    
        public virtual T_BPM_PROCESSCLASS T_BPM_PROCESSCLASS { get; set; }
    }
}
