//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BPM_PROCESSCLASS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_BPM_PROCESSCLASS()
        {
            this.T_BPM_PRCCLASS_LINK = new HashSet<T_BPM_PRCCLASS_LINK>();
            this.T_BPM_PROCESSCLASS_C_USER = new HashSet<T_BPM_PROCESSCLASS_C_USER>();
            this.T_BPM_TASK_AUTOASSIGNED = new HashSet<T_BPM_TASK_AUTOASSIGNED>();
            this.T_BPM_PROCESSCLASS_RIGHT_LINK = new HashSet<T_BPM_PROCESSCLASS_RIGHT_LINK>();
        }
    
        public string CID { get; set; }
        public string C_USER_CID { get; set; }
        public string C_USER_CODE { get; set; }
        public string C_USER_NAME { get; set; }
        public Nullable<System.DateTime> C_DATE { get; set; }
        public string U_USER_CID { get; set; }
        public string U_USER_CODE { get; set; }
        public Nullable<System.DateTime> U_DATE { get; set; }
        public string INFO_STATUS { get; set; }
        public string PRCCLASS_NAME { get; set; }
        public string SUPERCLASS_CID { get; set; }
        public string SUPERCLASS_NAME { get; set; }
        public string CLASS_PATH { get; set; }
        public string PRCCLASS_NEMO { get; set; }
        public Nullable<int> PRCCLASS_ORDER { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_BPM_PRCCLASS_LINK> T_BPM_PRCCLASS_LINK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_BPM_PROCESSCLASS_C_USER> T_BPM_PROCESSCLASS_C_USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_BPM_TASK_AUTOASSIGNED> T_BPM_TASK_AUTOASSIGNED { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_BPM_PROCESSCLASS_RIGHT_LINK> T_BPM_PROCESSCLASS_RIGHT_LINK { get; set; }
    }
}
