//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BPM_SYSTEM_SET
    {
        public string CID { get; set; }
        public string SET_CODE { get; set; }
        public string SET_NAME { get; set; }
        public Nullable<int> SET_TYPE { get; set; }
        public Nullable<int> SET_STATUS { get; set; }
        public string SET_VALUE { get; set; }
        public string CLASS_NAME { get; set; }
        public string MODULE_NAME { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_USER { get; set; }
        public string RESERVED_1 { get; set; }
        public string RESERVED_2 { get; set; }
        public string RESERVED_3 { get; set; }
        public string RESERVED_4 { get; set; }
        public string RESERVED_5 { get; set; }
        public string RESERVED_6 { get; set; }
        public string RESERVED_7 { get; set; }
        public string RESERVED_8 { get; set; }
        public string RESERVED_9 { get; set; }
        public string RESERVED_10 { get; set; }
    }
}
