//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BPM_PRC_APPROVAL
    {
        public string CID { get; set; }
        public string SYSTEM_CID { get; set; }
        public string SYSTEM_NAME { get; set; }
        public string PRC_NAME { get; set; }
        public int INCIDENT { get; set; }
        public string PRC_SUMMARY { get; set; }
        public string STEP_NAME { get; set; }
        public string TASKUSER_CID { get; set; }
        public string TASKUSER_CODE { get; set; }
        public string TASKUSER_ULT_CODE { get; set; }
        public string TASK_USER_NAME { get; set; }
        public string TASK_USER_DPT { get; set; }
        public string TASK_USER_DPT_PASS { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public Nullable<System.DateTime> OVER_DATE { get; set; }
        public string PM_STATUS { get; set; }
        public string TASK_ID { get; set; }
        public string LAST_STEP { get; set; }
        public string LAST_USER_CODE { get; set; }
        public string LAST_USER_NAME { get; set; }
        public Nullable<System.DateTime> DEALTIME { get; set; }
        public Nullable<System.DateTime> OVERTIME { get; set; }
        public string TASK_URL { get; set; }
        public string APPROVAL_OPINION { get; set; }
    }
}
