//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BPM_PRCCLASS_LINK
    {
        public string CID { get; set; }
        public string CLASS_CID { get; set; }
        public string CLASS_NAME { get; set; }
        public string PROCESSNAME { get; set; }
        public int CLASS_ORDER { get; set; }
    
        public virtual T_BPM_PROCESSCLASS T_BPM_PROCESSCLASS { get; set; }
    }
}
