//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BPM_PROCESSCLASS_C_USER
    {
        public string CID { get; set; }
        public string INFO_CID { get; set; }
        public string USER_CID { get; set; }
        public string USER_CODE { get; set; }
        public string JOB_CID { get; set; }
        public string JOB_NAME { get; set; }
        public string JOB_IS_MAIN { get; set; }
        public string DPT_CID { get; set; }
        public string DPT_NAME { get; set; }
    
        public virtual T_BPM_PROCESSCLASS T_BPM_PROCESSCLASS { get; set; }
    }
}
