//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TASKQUEUE
    {
        public string TASKID { get; set; }
        public Nullable<int> STATUS { get; set; }
        public byte[] LOCALSS { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> TASKTIME { get; set; }
        public string TASKUSER { get; set; }
        public string REFERER { get; set; }
        public Nullable<int> RETRIES { get; set; }
        public Nullable<System.DateTime> SUBMITTIME { get; set; }
        public string ID { get; set; }
        public string CLIENTID { get; set; }
        public byte[] P_C_INFO { get; set; }
        public string SUMMARY { get; set; }
        public Nullable<int> PRIORITY { get; set; }
        public Nullable<bool> DISABLEABORT { get; set; }
        public string MEMODATA { get; set; }
    }
}
