//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UltimusDBEntities : DbContext
    {
        public UltimusDBEntities()
            : base("name=UltimusDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GROUP> GROUPS { get; set; }
        public virtual DbSet<INCIDENT> INCIDENTS { get; set; }
        public virtual DbSet<INCIDENTS_ARCHIVE> INCIDENTS_ARCHIVE { get; set; }
        public virtual DbSet<INCIDENTS_BAK> INCIDENTS_BAK { get; set; }
        public virtual DbSet<PROCESSCONFIGURATION> PROCESSCONFIGURATIONs { get; set; }
        public virtual DbSet<PROCESS> PROCESSES { get; set; }
        public virtual DbSet<PROCESSSTEP> PROCESSSTEPS { get; set; }
        public virtual DbSet<REPORTSRIGHT> REPORTSRIGHTS { get; set; }
        public virtual DbSet<SERVERPREFERENCE> SERVERPREFERENCES { get; set; }
        public virtual DbSet<STEPACTIVATIONID> STEPACTIVATIONIDS { get; set; }
        public virtual DbSet<STEPACTIVATIONSYNC> STEPACTIVATIONSYNCs { get; set; }
        public virtual DbSet<StudioConfig_Domains> StudioConfig_Domains { get; set; }
        public virtual DbSet<StudioConfig_LDAPDomains> StudioConfig_LDAPDomains { get; set; }
        public virtual DbSet<StudioConfig_Repositories> StudioConfig_Repositories { get; set; }
        public virtual DbSet<StudioConfig_Servers> StudioConfig_Servers { get; set; }
        public virtual DbSet<StudioConfig_UserRepositories> StudioConfig_UserRepositories { get; set; }
        public virtual DbSet<StudioConfig_Users> StudioConfig_Users { get; set; }
        public virtual DbSet<StudioConfig_UserServers> StudioConfig_UserServers { get; set; }
        public virtual DbSet<SUBPROC> SUBPROCS { get; set; }
        public virtual DbSet<T_BPM_AWOKE_SET> T_BPM_AWOKE_SET { get; set; }
        public virtual DbSet<T_BPM_PRC_APPROVAL> T_BPM_PRC_APPROVAL { get; set; }
        public virtual DbSet<T_BPM_PRC_RGT> T_BPM_PRC_RGT { get; set; }
        public virtual DbSet<T_BPM_PRCCLASS_LINK> T_BPM_PRCCLASS_LINK { get; set; }
        public virtual DbSet<T_BPM_PROCESSCLASS> T_BPM_PROCESSCLASS { get; set; }
        public virtual DbSet<T_BPM_PROCESSCLASS_C_USER> T_BPM_PROCESSCLASS_C_USER { get; set; }
        public virtual DbSet<T_BPM_PROCESSCLASS_RIGHT_LINK> T_BPM_PROCESSCLASS_RIGHT_LINK { get; set; }
        public virtual DbSet<T_BPM_READ_KNOW> T_BPM_READ_KNOW { get; set; }
        public virtual DbSet<T_BPM_SYSTEM_SET> T_BPM_SYSTEM_SET { get; set; }
        public virtual DbSet<T_BPM_TASK_AUTOASSIGNED> T_BPM_TASK_AUTOASSIGNED { get; set; }
        public virtual DbSet<TASKQUEUE> TASKQUEUEs { get; set; }
        public virtual DbSet<TASK> TASKS { get; set; }
        public virtual DbSet<TASKS_ARCHIVE> TASKS_ARCHIVE { get; set; }
        public virtual DbSet<TASKS_BAK> TASKS_BAK { get; set; }
        public virtual DbSet<ULTIMUSREPALERT> ULTIMUSREPALERTS { get; set; }
        public virtual DbSet<ULTIMUSREPORT> ULTIMUSREPORTS { get; set; }
        public virtual DbSet<ULTVIEW> ULTVIEWS { get; set; }
        public virtual DbSet<VIEWFOLDER> VIEWFOLDERS { get; set; }
        public virtual DbSet<FILTER> FILTERS { get; set; }
        public virtual DbSet<LOGACTION> LOGACTIONS { get; set; }
        public virtual DbSet<LOGACTIONS_ARCHIVE> LOGACTIONS_ARCHIVE { get; set; }
        public virtual DbSet<LOGACTIONS_BAK> LOGACTIONS_BAK { get; set; }
        public virtual DbSet<LOGEVENT> LOGEVENTS { get; set; }
        public virtual DbSet<LOGEVENTS_ARCHIVE> LOGEVENTS_ARCHIVE { get; set; }
        public virtual DbSet<LOGEVENTS_BAK> LOGEVENTS_BAK { get; set; }
        public virtual DbSet<MEMBER> MEMBERS { get; set; }
        public virtual DbSet<PROCESSACCESSRIGHT> PROCESSACCESSRIGHTS { get; set; }
        public virtual DbSet<StudioConfig_AccessRights> StudioConfig_AccessRights { get; set; }
        public virtual DbSet<TRUSTEDUSER> TRUSTEDUSERS { get; set; }
        public virtual DbSet<USERSERVERPREFERENCE> USERSERVERPREFERENCES { get; set; }
    }
}
