//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERSERVERPREFERENCE
    {
        public string USERFRUID { get; set; }
        public string SERVERNAME { get; set; }
        public string LOGINNAME { get; set; }
        public string PASSWORD { get; set; }
        public string DOMAIN { get; set; }
        public bool VISIBLE { get; set; }
    
        public virtual SERVERPREFERENCE SERVERPREFERENCE { get; set; }
    }
}
