using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace IDAL
{
	public partial interface IDBSession
	{
    IFILTERDAL IFILTERDAL{get;set;}
    IGROUPDAL IGROUPDAL{get;set;}
    IINCIDENTDAL IINCIDENTDAL{get;set;}
    IINCIDENTS_ARCHIVEDAL IINCIDENTS_ARCHIVEDAL{get;set;}
    IINCIDENTS_BAKDAL IINCIDENTS_BAKDAL{get;set;}
    ILOGACTIONDAL ILOGACTIONDAL{get;set;}
    ILOGACTIONS_ARCHIVEDAL ILOGACTIONS_ARCHIVEDAL{get;set;}
    ILOGACTIONS_BAKDAL ILOGACTIONS_BAKDAL{get;set;}
    ILOGEVENTDAL ILOGEVENTDAL{get;set;}
    ILOGEVENTS_ARCHIVEDAL ILOGEVENTS_ARCHIVEDAL{get;set;}
    ILOGEVENTS_BAKDAL ILOGEVENTS_BAKDAL{get;set;}
    IMEMBERDAL IMEMBERDAL{get;set;}
    IPROCESSDAL IPROCESSDAL{get;set;}
    IPROCESSACCESSRIGHTDAL IPROCESSACCESSRIGHTDAL{get;set;}
    IPROCESSCONFIGURATIONDAL IPROCESSCONFIGURATIONDAL{get;set;}
    IPROCESSSTEPDAL IPROCESSSTEPDAL{get;set;}
    IREPORTSRIGHTDAL IREPORTSRIGHTDAL{get;set;}
    ISERVERPREFERENCEDAL ISERVERPREFERENCEDAL{get;set;}
    ISTEPACTIVATIONIDDAL ISTEPACTIVATIONIDDAL{get;set;}
    ISTEPACTIVATIONSYNCDAL ISTEPACTIVATIONSYNCDAL{get;set;}
    IStudioConfig_AccessRightsDAL IStudioConfig_AccessRightsDAL{get;set;}
    IStudioConfig_DomainsDAL IStudioConfig_DomainsDAL{get;set;}
    IStudioConfig_LDAPDomainsDAL IStudioConfig_LDAPDomainsDAL{get;set;}
    IStudioConfig_RepositoriesDAL IStudioConfig_RepositoriesDAL{get;set;}
    IStudioConfig_ServersDAL IStudioConfig_ServersDAL{get;set;}
    IStudioConfig_UserRepositoriesDAL IStudioConfig_UserRepositoriesDAL{get;set;}
    IStudioConfig_UsersDAL IStudioConfig_UsersDAL{get;set;}
    IStudioConfig_UserServersDAL IStudioConfig_UserServersDAL{get;set;}
    ISUBPROCDAL ISUBPROCDAL{get;set;}
    IT_BPM_AWOKE_SETDAL IT_BPM_AWOKE_SETDAL{get;set;}
    IT_BPM_PRC_APPROVALDAL IT_BPM_PRC_APPROVALDAL{get;set;}
    IT_BPM_PRC_RGTDAL IT_BPM_PRC_RGTDAL{get;set;}
    IT_BPM_PRCCLASS_LINKDAL IT_BPM_PRCCLASS_LINKDAL{get;set;}
    IT_BPM_PROCESSCLASSDAL IT_BPM_PROCESSCLASSDAL{get;set;}
    IT_BPM_PROCESSCLASS_C_USERDAL IT_BPM_PROCESSCLASS_C_USERDAL{get;set;}
    IT_BPM_PROCESSCLASS_RIGHT_LINKDAL IT_BPM_PROCESSCLASS_RIGHT_LINKDAL{get;set;}
    IT_BPM_READ_KNOWDAL IT_BPM_READ_KNOWDAL{get;set;}
    IT_BPM_SYSTEM_SETDAL IT_BPM_SYSTEM_SETDAL{get;set;}
    IT_BPM_TASK_AUTOASSIGNEDDAL IT_BPM_TASK_AUTOASSIGNEDDAL{get;set;}
    ITASKDAL ITASKDAL{get;set;}
    ITASKQUEUEDAL ITASKQUEUEDAL{get;set;}
    ITASKS_ARCHIVEDAL ITASKS_ARCHIVEDAL{get;set;}
    ITASKS_BAKDAL ITASKS_BAKDAL{get;set;}
    ITRUSTEDUSERDAL ITRUSTEDUSERDAL{get;set;}
    IULTIMUSREPALERTDAL IULTIMUSREPALERTDAL{get;set;}
    IULTIMUSREPORTDAL IULTIMUSREPORTDAL{get;set;}
    IULTVIEWDAL IULTVIEWDAL{get;set;}
    IUSERSERVERPREFERENCEDAL IUSERSERVERPREFERENCEDAL{get;set;}
    IVIEWFOLDERDAL IVIEWFOLDERDAL{get;set;}
	}
}
